# -- Site Configuration --

# baseURL = "https://hemangshrimali.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]